---
- name: Deploy Kubernetes Cluster
  hosts: all
  become: yes

  # Skip the built-in fact gathering until after Python is in place
  gather_facts: false

  pre_tasks:
    - name: Bootstrap Python3 on Debian/Ubuntu
      raw: |
        if command -v apt-get &>/dev/null; then
          apt-get update && apt-get install -y python3 python3-apt
        fi
      args:
        warn: false
      changed_when: false

    - name: Bootstrap Python3 on RHEL/CentOS
      raw: |
        if command -v yum &>/dev/null; then
          yum install -y python3
        fi
      args:
        warn: false
      changed_when: false

    - name: Wait until python3 is available
      wait_for:
        path: /usr/bin/python3
        timeout: 300

    - name: Tell Ansible to use Python3 from now on
      set_fact:
        ansible_python_interpreter: /usr/bin/python3

    - name: Gather facts
      setup:

  vars:
    kube_version: "1.29.2"
    pod_network_cidr: "10.244.0.0/16"

  # Your handlers remain unchanged
  handlers:
    - name: Restart containerd
      systemd:
        name: containerd
        state: restarted

    - name: Restart docker
      systemd:
        name: docker
        state: restarted

    - name: Reboot system
      reboot:
        msg: "Reboot required for kernel changes"
        reboot_timeout: 600

  # Main tasks
  tasks:
    - name: Configure all nodes
      include_tasks: tasks/common.yml

    - name: Configure master nodes
      include_tasks: tasks/master.yml
      when: inventory_hostname in groups.master

    - name: Configure worker nodes
      include_tasks: tasks/worker.yml
      when: inventory_hostname in groups.workers

  post_tasks:
    - name: Apply RBAC fix
      shell: |
        kubectl create clusterrolebinding cluster-admin-binding \
          --clusterrole=cluster-admin \
          --user=system:serviceaccount:kube-system:default
      delegate_to: "{{ groups.master[0] }}"
      run_once: yes
      ignore_errors: yes

    - name: Verify cluster health
      shell: |
        kubectl get nodes
        kubectl get pods -n kube-system
      register: cluster_health
      until: cluster_health.rc == 0
      retries: 10
      delay: 30
      delegate_to: "{{ groups.master[0] }}"
      run_once: yes

    - name: Show final status
      debug:
        msg: "Kubernetes cluster deployed successfully! Nodes:\n{{ cluster_health.stdout }}"
      run_once: yes
      when: cluster_health.rc == 0
