---
- name: Configure system prerequisites
  block:
    - name: Install firewalld dependencies
      dnf:
        name: python3-firewalld
        state: present
      when: ansible_os_family == "RedHat"

    - name: Install SELinux dependencies
      dnf:
        name: libselinux-python3
        state: present
      when: ansible_os_family == "RedHat"

    - name: Install python3-pyudev for modprobe
      dnf:
        name: python3-pyudev
        state: present
      when: ansible_os_family == "RedHat"

    - name: Check if SELinux is installed
      command: sestatus
      register: selinux_status
      ignore_errors: yes
      changed_when: false

    - name: Set SELinux to permissive
      ansible.posix.selinux:
        policy: targeted
        state: permissive
      when: selinux_status.rc == 0
      notify: Reboot system

    - name: Disable SELinux permanently
      lineinfile:
        path: /etc/selinux/config
        regexp: '^SELINUX='
        line: 'SELINUX=disabled'
        validate: '/usr/sbin/sestatus %s'
      when: selinux_status.rc == 0

    - name: Disable swap
      block:
        - name: Disable active swap
          command: swapoff -a
        - name: Disable swap in fstab
          replace:
            path: /etc/fstab
            regexp: '^([^#].*?\bswap\b.*)$'
            replace: '#\1'
            backup: yes
      notify: Reboot system

    - name: Load kernel modules
      community.general.modprobe:
        name: "{{ item }}"
        state: present
      with_items:
        - br_netfilter
        - overlay

    - name: Configure sysctl
      sysctl:
        name: "{{ item.key }}"
        value: "{{ item.value }}"
        state: present
        reload: yes
      with_dict:
        net.bridge.bridge-nf-call-ip6tables: 1
        net.bridge.bridge-nf-call-iptables: 1
        net.ipv4.ip_forward: 1

    - name: Persist kernel settings
      copy:
        dest: /etc/modules-load.d/k8s.conf
        content: |
          br_netfilter
          overlay

    - name: Flush handlers to apply reboots
      meta: flush_handlers

    - name: Wait for node to be reachable after reboot
      wait_for_connection:
        timeout: 600
      when: ansible_reboot_pending | default(false)

- name: Configure container runtime
  block:
    - name: Add Docker CE repository (CentOS 7)
      yum_repository:
        name: docker-ce
        description: Docker CE Stable
        baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
        gpgkey: https://download.docker.com/linux/centos/gpg
        gpgcheck: yes
        enabled: yes
      when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

    - name: Add Docker CE repository (CentOS 8)
      dnf_repository:
        name: docker-ce
        description: Docker CE Stable
        baseurl: https://download.docker.com/linux/centos/8/$basearch/stable
        gpgkey: https://download.docker.com/linux/centos/gpg
        gpgcheck: yes
        enabled: yes
      when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "8"

    - name: Install containerd.io
      dnf:
        name: containerd.io
        state: present

    - name: Configure containerd
      copy:
        dest: /etc/containerd/config.toml
        content: |
          version = 2
          [plugins."io.containerd.grpc.v1.cri"]
            sandbox_image = "registry.k8s.io/pause:3.9"
            [plugins."io.containerd.grpc.v1.cri".containerd]
              default_runtime_name = "runc"
              [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
                runtime_type = "io.containerd.runc.v2"
                [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
                  SystemdCgroup = true
      notify: Restart containerd

    - name: Install Docker CE
      dnf:
        name:
          - docker-ce
          - docker-ce-cli
        state: present

    - name: Configure Docker daemon
      copy:
        dest: /etc/docker/daemon.json
        content: |
          {
            "exec-opts": ["native.cgroupdriver=systemd"],
            "log-driver": "json-file",
            "log-opts": {
              "max-size": "100m"
            },
            "storage-driver": "overlay2"
          }
      notify: Restart docker

- name: Configure firewall
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
  with_items:
    - 6443/tcp
    - 2379-2380/tcp
    - 10250/tcp
    - 10259/tcp
    - 10257/tcp
