---
- name: Install required packages
  block:
    - name: Install containerd
      yum:
        name: containerd
        state: present

    - name: Enable and start containerd
      systemd:
        name: containerd
        enabled: yes
        state: started

- name: Install Kubernetes components
  block:
    - name: Add Kubernetes repo
      yum_repository:
        name: kubernetes
        description: Kubernetes RPM Repository
        baseurl: https://pkgs.k8s.io/core:/stable:/v1.29/rpm/
        gpgkey: https://pkgs.k8s.io/core:/stable:/v1.29/rpm/repodata/repomd.xml.key
        gpgcheck: yes
        repo_gpgcheck: no
        enabled: yes

    - name: Install Kubernetes packages
      yum:
        name:
          - kubelet-{{ kube_version }}
          - kubeadm-{{ kube_version }}
          - kubectl-{{ kube_version }}
        state: present

    - name: Enable kubelet
      systemd:
        name: kubelet
        enabled: yes

- name: Initialize cluster
  block:
    - name
