
---
- name: Prepare Kubernetes components
  block:
    - name: Install dependencies
      yum:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
        state: present

    - name: Add Kubernetes repository
      yum_repository:
        name: kubernetes
        description: Kubernetes RPM Repository
        baseurl: https://pkgs.k8s.io/core:/stable:/v1.29/rpm/
        gpgkey: https://pkgs.k8s.io/core:/stable:/v1.29/rpm/repodata/repomd.xml.key
        gpgcheck: yes
        repo_gpgcheck: yes
        enabled: yes

    - name: Install worker packages
      yum:
        name:
          - kubelet-{{ kube_version }}
          - kubeadm-{{ kube_version }}
        state: present

    - name: Add Docker and containerd repository
      yum_repository:
        name: docker-ce
        description: Docker CE Repository
        baseurl: https://download.docker.com/linux/centos/7/x86_64/stable/
        gpgkey: https://download.docker.com/linux/centos/gpg
        gpgcheck: yes
        enabled: yes

    - name: Install container runtime (containerd)
      yum:
        name:
          - containerd.io
        state: present

    - name: Configure containerd
      shell: |
        mkdir -p /etc/containerd
        containerd config default > /etc/containerd/config.toml
        sed -i 's/SystemdCgroup = false/SystemdCgroup = true/' /etc/containerd/config.toml

    - name: Enable and start containerd
      systemd:
        name: containerd
        enabled: yes
        state: restarted

    - name: Ensure kubelet is enabled
      systemd:
        name: kubelet
        enabled: yes
        state: restarted

- name: Join cluster process
  block:
    - name: Fetch join command from master
      command: cat /tmp/join-command.sh
      register: join_command
      delegate_to: "{{ groups.master[0] }}"
      run_once: yes
      ignore_errors: yes

    - name: Regenerate join command if missing
      shell: |
        kubeadm token create --print-join-command > /tmp/join-command.sh
        chmod 600 /tmp/join-command.sh
      delegate_to: "{{ groups.master[0] }}"
      run_once: yes
      when: join_command.failed

    # Critical missing step: Execute the join command on workers
    - name: Join worker to cluster
      command: "{{ join_command.stdout }}"
      when: inventory_hostname in groups.workers

