# tasks/worker.yml
---
- name: Ensure /home/pfe/.ssh exists on worker
  file:
    path: /home/pfe/.ssh
    state: directory
    owner: pfe
    group: pfe
    mode: '0700'

- name: Authorize controller’s SSH key on worker
  authorized_key:
    user: pfe
    key: "{{ hostvars[groups.master[0]].controller_pubkey }}"
    state: present

- name: Install & configure containerd on worker
  block:
    - name: Install dependencies
      yum:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
        state: present

    - name: Add Kubernetes repo
      yum_repository:
        name: kubernetes
        description: Kubernetes RPM Repository
        baseurl: https://pkgs.k8s.io/core:/stable:/v1.29/rpm/
        gpgkey: https://pkgs.k8s.io/core:/stable:/v1.29/rpm/repodata/repomd.xml.key
        gpgcheck: yes
        repo_gpgcheck: yes
        enabled: yes

    - name: Install kubelet and kubeadm
      yum:
        name:
          - kubelet-{{ kube_version }}
          - kubeadm-{{ kube_version }}
        state: present

    - name: Install containerd runtime
      yum:
        name: containerd.io
        state: present

    - name: Configure containerd for systemd cgroup
      shell: |
        mkdir -p /etc/containerd
        containerd config default > /etc/containerd/config.toml
        sed -i 's/SystemdCgroup = false/SystemdCgroup = true/' /etc/containerd/config.toml

    - name: Enable and start containerd
      systemd:
        name: containerd
        enabled: yes
        state: restarted

    - name: Enable kubelet
      systemd:
        name: kubelet
        enabled: yes
        state: restarted

- name: Fetch join command from master
  command: cat /tmp/join-command.sh
  register: join_command
  delegate_to: "{{ groups.master[0] }}"
  run_once: yes
  ignore_errors: yes

- name: Recreate join command if missing
  shell: kubeadm token create --print-join-command > /tmp/join-command.sh
  delegate_to: "{{ groups.master[0] }}"
  run_once: yes
  when: join_command.failed

- name: Execute join command
  command: "{{ join_command.stdout }}"
  when: inventory_hostname in groups.workers
